### ISSUE TITLE
「集群模式」数据存储到HIVE报错

### ISSUE THREAD

**Issue by saksim** [saksim/jws#12]
集群提交后，查看yarn日志
yarn logs -applicationId application_xxxxxxx_xxxx

问题描述：

Traceback (most recent call last):
  File "Getw2vv2.py", line 157, in <module>
    weiwei_try.toHiveTablev2(df=result,spark=spark)
  File "Getw2vv2.py", line 89, in toHiveTablev2
    df = df.withColumn("result",col("result")[3])
  File "/opt/cloudera/parcels/SPARK2-2.3.0.cloudera4-1.cdh5.13.3.p0.611179/lib/spark2/python/pyspark/sql/dataframe.py", line 1849, in withColumn
    return DataFrame(self._jdf.withColumn(colName, col._jc), self.sql_ctx)
  File "/opt/cloudera/parcels/SPARK2-2.3.0.cloudera4-1.cdh5.13.3.p0.611179/lib/spark2/python/lib/py4j-0.10.7-src.zip/py4j/java_gateway.py", line 1257, in __call__
  File "/opt/cloudera/parcels/SPARK2-2.3.0.cloudera4-1.cdh5.13.3.p0.611179/lib/spark2/python/pyspark/sql/utils.py", line 69, in deco
    raise AnalysisException(s.split(': ', 1)[1], stackTrace)
pyspark.sql.utils.AnalysisException: "Can't extract value from result#205: need struct type but got vector;"

**Comment by saksim** [comment]
解决方案：
直接存入HIVE后，使用STRETURE在HIVE内抽取。例如列名为result，里面有”values“,则可以选择result.values 然后又40个或者N个特征 需要一个一个抽取

如此，只需要在外层添加一个脚本，用于抽取数据即可！
**SELECT XXXX,……,YYYY, RESULT.VALUES[0] AS FEATURE1,RESULT.VALUES[1] AS FEATURE2,……
FROM XYZ_TABLE**
