### ISSUE TITLE
脚本传入特征，训练报错

### ISSUE THREAD

**Issue by saksim** [saksim/jws#15]
环境：
CENTOS7

调用：
spark2-submit --master local[4]                /data/heweiwei/191015/src/mainv6.py --path /data/heweiwei/stopWords.txt                 --path0 /data/heweiwei/191026/data/final_data.txt                 --path1 /data/heweiwei/191026/data/final_data.txt                 --model_name "clues_Bcard" --type "xgb"                 --fitv2_kol                 --printPredictResult                 --cat_feature reason                --num_feature day                --num_feature hour                --num_feature minute                --num_feature FEATURE_1                 --num_feature FEATURE_2                --num_feature FEATURE_3                --num_feature FEATURE_4                --num_feature FEATURE0                --num_feature FEATURE1                --num_feature FEATURE2                --num_feature FEATURE3                --num_feature FEATURE4                --num_feature FEATURE5                --num_feature FEATURE6                --num_feature FEATURE7                --num_feature FEATURE8                --num_feature FEATURE9                --num_feature FEATURE10                --num_feature FEATURE11                --num_feature FEATURE12                --num_feature FEATURE13                --num_feature FEATURE14                --num_feature FEATURE15                --num_feature FEATURE16                --num_feature FEATURE17                --num_feature FEATURE18                --num_feature FEATURE19                --num_feature FEATURE20                --num_feature FEATURE21                --num_feature FEATURE22                --num_feature FEATURE23                --num_feature FEATURE24                --num_feature FEATURE25                --num_feature FEATURE26                --num_feature FEATURE27                --num_feature FEATURE28                --num_feature FEATURE29                --num_feature FEATURE30                --num_feature FEATURE31                --num_feature FEATURE32                --num_feature FEATURE33                --num_feature FEATURE34                --num_feature FEATURE35                --num_feature FEATURE36                --num_feature FEATURE37                --num_feature FEATURE38                --num_feature FEATURE39                --out_path /data/heweiwei/191022/model                --method 'featureunion'                --suffix "1026_47n1c_v1" > /data/heweiwei/191026/log/train_clues_Bcardv1 2>&1 &

报错日志：

Building prefix dict from the default dictionary ...
Loading model from cache /tmp/jieba.cache
Loading model cost 0.806 seconds.
Prefix dict has been built succesfully.
Training on Datas.......
Numbers of Data:  308330
cat;num;tet column as follows:  ['reason'] ['day', 'hour', 'minute', 'FEATURE_1', 'FEATURE_2', 'FEATURE_3', 'FEATURE_4', 'FEATURE0', 'FEATURE1', 'FEATURE2', 'FEATURE3', 'FEATURE4', 'FEATURE5', 'FEATURE6', 'FEATURE7', 'FEATURE8', 'FEATURE9', 'FEATURE10', 'FEATURE11', 'FEATURE12', 'FEATURE13', 'FEATURE14', 'FEATURE15', 'FEATURE16', 'FEATURE17', 'FEATURE18', 'FEATURE19', 'FEATURE20', 'FEATURE21', 'FEATURE22', 'FEATURE23', 'FEATURE24', 'FEATURE25', 'FEATURE26', 'FEATURE27', 'FEATURE28', 'FEATURE29', 'FEATURE30', 'FEATURE31', 'FEATURE32', 'FEATURE33', 'FEATURE34', 'FEATURE35', 'FEATURE36', 'FEATURE37', 'FEATURE38', 'FEATURE39']
Get numeric-data:  ['day', 'hour', 'minute', 'FEATURE_1', 'FEATURE_2', 'FEATURE_3', 'FEATURE_4', 'FEATURE0', 'FEATURE1', 'FEATURE2', 'FEATURE3', 'FEATURE4', 'FEATURE5', 'FEATURE6', 'FEATURE7', 'FEATURE8', 'FEATURE9', 'FEATURE10', 'FEATURE11', 'FEATURE12', 'FEATURE13', 'FEATURE14', 'FEATURE15', 'FEATURE16', 'FEATURE17', 'FEATURE18', 'FEATURE19', 'FEATURE20', 'FEATURE21', 'FEATURE22', 'FEATURE23', 'FEATURE24', 'FEATURE25', 'FEATURE26', 'FEATURE27', 'FEATURE28', 'FEATURE29', 'FEATURE30', 'FEATURE31', 'FEATURE32', 'FEATURE33', 'FEATURE34', 'FEATURE35', 'FEATURE36', 'FEATURE37', 'FEATURE38', 'FEATURE39']
The selected colums:  ['day', 'hour', 'minute', 'FEATURE_1', 'FEATURE_2', 'FEATURE_3', 'FEATURE_4', 'FEATURE0', 'FEATURE1', 'FEATURE2', 'FEATURE3', 'FEATURE4', 'FEATURE5', 'FEATURE6', 'FEATURE7', 'FEATURE8', 'FEATURE9', 'FEATURE10', 'FEATURE11', 'FEATURE12', 'FEATURE13', 'FEATURE14', 'FEATURE15', 'FEATURE16', 'FEATURE17', 'FEATURE18', 'FEATURE19', 'FEATURE20', 'FEATURE21', 'FEATURE22', 'FEATURE23', 'FEATURE24', 'FEATURE25', 'FEATURE26', 'FEATURE27', 'FEATURE28', 'FEATURE29', 'FEATURE30', 'FEATURE31', 'FEATURE32', 'FEATURE33', 'FEATURE34', 'FEATURE35', 'FEATURE36', 'FEATURE37', 'FEATURE38', 'FEATURE39']
Traceback (most recent call last):
  File "/data/191015/src/mainv6.py", line 776, in <module>
    main()
  File "/data/191015/src/mainv6.py", line 679, in main
    cat_col=cat_feature, num_col=num_feature, method=method)
  File "/data/191015/src/mainv6.py", line 286, in fitv2_kol
    base_model = base.fit(train_df.drop(train_label,axis=1), train_df[train_label])
  File "/opt/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py", line 265, in fit
    Xt, fit_params = self._fit(X, y, **fit_params)
  File "/opt/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py", line 230, in _fit
    **fit_params_steps[name])
  File "/opt/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/memory.py", line 342, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py", line 614, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/opt/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py", line 793, in fit_transform
    for name, trans, weight in self._iter())
  File "/opt/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 917, in __call__
    if self.dispatch_one_batch(iterator):
  File "/opt/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 759, in dispatch_one_batch
    self._dispatch(tasks)
  File "/opt/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 716, in _dispatch
    job = self._backend.apply_async(batch, callback=cb)
  File "/opt/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 182, in apply_async
    result = ImmediateResult(func)
  File "/opt/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/_parallel_backends.py", line 549, in __init__
    self.results = batch()
  File "/opt/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/opt/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "/opt/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py", line 614, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/opt/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py", line 298, in fit_transform
    Xt, fit_params = self._fit(X, y, **fit_params)
  File "/opt/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py", line 230, in _fit
    **fit_params_steps[name])
  File "/opt/anaconda3/lib/python3.7/site-packages/sklearn/externals/joblib/memory.py", line 342, in __call__
    return self.func(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.7/site-packages/sklearn/pipeline.py", line 614, in _fit_transform_one
    res = transformer.fit_transform(X, y, **fit_params)
  File "/opt/anaconda3/lib/python3.7/site-packages/sklearn/base.py", line 467, in fit_transform
    return self.fit(X, y, **fit_params).transform(X)
  File "/data/191015/src/mainv6.py", line 45, in transform
    df_num = cpy_dfv[self.col]
  File "/opt/anaconda3/lib/python3.7/site-packages/pandas/core/frame.py", line 2934, in __getitem__
    raise_missing=True)
  File "/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1354, in _convert_to_indexer
    return self._get_listlike_indexer(obj, axis, **kwargs)[1]
  File "/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1161, in _get_listlike_indexer
    raise_missing=raise_missing)
  File "/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py", line 1252, in _validate_read_indexer
    raise KeyError("{} not in index".format(not_found))
KeyError: "['FEATURE5', 'FEATURE14', 'FEATURE0', 'FEATURE1', 'FEATURE2', 'FEATURE26', 'FEATURE37', 'FEATURE24', 'FEATURE25', 'FEATURE18', 'FEATURE17', 'FEATURE8', 'FEATURE15', 'FEATURE16', 'FEATURE22', 'FEATURE21', 'FEATURE11', 'FEATURE29', 'FEATURE13', 'FEATURE28', 'FEATURE30', 'FEATURE_1', 'FEATURE7', 'FEATURE_3', 'FEATURE10', 'FEATURE39', 'FEATURE_2', 'FEATURE33', 'FEATURE34', 'FEATURE3', 'FEATURE19', 'FEATURE6', 'FEATURE36', 'FEATURE_4', 'FEATURE23', 'FEATURE35', 'FEATURE12', 'FEATURE32', 'FEATURE31', 'FEATURE27', 'FEATURE9', 'FEATURE4', 'FEATURE38', 'FEATURE20'] not in index"
19/10/26 14:26:04 INFO util.ShutdownHookManager: Shutdown hook called
19/10/26 14:26:04 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-c21bafa6-6b9d-43b3-9c16-461eb664d50a

**Comment by saksim** [comment]
解决方案：
`**1）原因：是由于PYTHON的PANDAS内的列名，对大小写非常的敏感！！！**`

2) 解决方案：全部按照输出的列名，传入列名
spark2-submit --master local[4] \
               /data/heweiwei/191015/src/mainv6.py --path /data/heweiwei/stopWords.txt  \
               --path0 /data/heweiwei/191026/data/final_data.txt  \
               --path1 /data/heweiwei/191026/data/final_data.txt  \
               --model_name "clues_Bcard" --type "xgb"  \
               --fitv2_kol  \
               --printPredictResult  \
               --cat_feature reason \
               --num_feature day \
               --num_feature hour \
               --num_feature minute \
               --num_feature feature_1  \
               --num_feature feature_2 \
               --num_feature feature_3 \
               --num_feature feature_4 \
               --num_feature feature0 \
               --num_feature feature1 \
               --num_feature feature2 \
               --num_feature feature3 \
               --num_feature feature4 \
               --num_feature feature5 \
               --num_feature feature6 \
               --num_feature feature7 \
               --num_feature feature8 \
               --num_feature feature9 \
               --num_feature feature10 \
               --num_feature feature11 \
               --num_feature feature12 \
               --num_feature feature13 \
               --num_feature feature14 \
               --num_feature feature15 \
               --num_feature feature16 \
               --num_feature feature17 \
               --num_feature feature18 \
               --num_feature feature19 \
               --num_feature feature20 \
               --num_feature feature21 \
               --num_feature feature22 \
               --num_feature feature23 \
               --num_feature feature24 \
               --num_feature feature25 \
               --num_feature feature26 \
               --num_feature feature27 \
               --num_feature feature28 \
               --num_feature feature29 \
               --num_feature feature30 \
               --num_feature feature31 \
               --num_feature feature32 \
               --num_feature feature33 \
               --num_feature feature34 \
               --num_feature feature35 \
               --num_feature feature36 \
               --num_feature feature37 \
               --num_feature feature38 \
               --num_feature feature39 \
               --out_path /data/heweiwei/191022/model \
               --method 'featureunion' \
               --suffix "1026_47n1c_v1" > /data/heweiwei/191026/log/train_clues_Bcardv1 2>&1 &
