### ISSUE TITLE
从PYTHON的DATAFRAME到SPARK的DATAFRAME出现问题

### ISSUE THREAD

**Issue by saksim** [saksim/jws#7]
问题描述：
19/10/10 11:23:55 INFO internal.SharedState: Warehouse path is '/user/hive/warehouse'.
19/10/10 11:23:55 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@4426a744{/SQL,null,AVAILABLE,@Spark}
19/10/10 11:23:55 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@34059c77{/SQL/json,null,AVAILABLE,@Spark}
19/10/10 11:23:55 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@17d0fe7f{/SQL/execution,null,AVAILABLE,@Spark}
19/10/10 11:23:55 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@5def1128{/SQL/execution/json,null,AVAILABLE,@Spark}
19/10/10 11:23:55 INFO handler.ContextHandler: Started o.s.j.s.ServletContextHandler@420a2e9d{/static/sql,null,AVAILABLE,@Spark}
19/10/10 11:23:55 INFO state.StateStoreCoordinatorRef: Registered StateStoreCoordinator endpoint
19/10/10 11:23:55 WARN lineage.LineageWriter: Lineage directory /var/log/spark2/lineage doesn't exist or is not writable. Lineage for this application will be disabled.
19/10/10 11:23:55 INFO util.Utils: Extension com.cloudera.spark.lineage.NavigatorQueryListener not being initialized.
Spark has been created..........
SAVING PANDAS DATAFRAME TO SPARK DATAFRAME.................
Traceback (most recent call last):
  File "/data/heweiwei/191008/src/mainv5.py", line 558, in <module>
    main()
  File "/data/heweiwei/191008/src/mainv5.py", line 544, in main
    pyDF2SparkDFwithPartition(result,spark,table_name,partition)
  File "/data/heweiwei/191008/src/mainv5.py", line 356, in pyDF2SparkDFwithPartition
    result = spark.createDataFrame(df)
  File "/opt/cloudera/parcels/SPARK2-2.3.0.cloudera4-1.cdh5.13.3.p0.611179/lib/spark2/python/lib/pyspark.zip/pyspark/sql/session.py", line 725, in createDataFrame
  File "/opt/cloudera/parcels/SPARK2-2.3.0.cloudera4-1.cdh5.13.3.p0.611179/lib/spark2/python/lib/pyspark.zip/pyspark/sql/session.py", line 410, in _createFromLocal
  File "/opt/cloudera/parcels/SPARK2-2.3.0.cloudera4-1.cdh5.13.3.p0.611179/lib/spark2/python/lib/pyspark.zip/pyspark/sql/session.py", line 342, in _inferSchemaFromList
  File "/opt/cloudera/parcels/SPARK2-2.3.0.cloudera4-1.cdh5.13.3.p0.611179/lib/spark2/python/lib/pyspark.zip/pyspark/sql/types.py", line 1133, in _merge_type
  File "/opt/cloudera/parcels/SPARK2-2.3.0.cloudera4-1.cdh5.13.3.p0.611179/lib/spark2/python/lib/pyspark.zip/pyspark/sql/types.py", line 1133, in <listcomp>
  File "/opt/cloudera/parcels/SPARK2-2.3.0.cloudera4-1.cdh5.13.3.p0.611179/lib/spark2/python/lib/pyspark.zip/pyspark/sql/types.py", line 1126, in _merge_type
TypeError: field area_name: Can not merge type <class 'pyspark.sql.types.StringType'> and <class 'pyspark.sql.types.DoubleType'>
19/10/10 11:23:58 INFO spark.SparkContext: Invoking stop() from shutdown hook
19/10/10 11:23:58 INFO server.AbstractConnector: Stopped Spark@1f8883d9{HTTP/1.1,[http/1.1]}{0.0.0.0:4040}
19/10/10 11:23:58 INFO ui.SparkUI: Stopped Spark web UI at http://slave7:4040
19/10/10 11:23:59 INFO spark.MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
19/10/10 11:23:59 INFO memory.MemoryStore: MemoryStore cleared
19/10/10 11:23:59 INFO storage.BlockManager: BlockManager stopped
19/10/10 11:23:59 INFO storage.BlockManagerMaster: BlockManagerMaster stopped
19/10/10 11:23:59 INFO scheduler.OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
19/10/10 11:23:59 INFO spark.SparkContext: Successfully stopped SparkContext
19/10/10 11:23:59 INFO util.ShutdownHookManager: Shutdown hook called
19/10/10 11:23:59 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-43e0f38a-ec55-4052-9c64-8f053347854b
19/10/10 11:23:59 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-8029defe-a67f-4955-b167-21f0e1158320
19/10/10 11:23:59 INFO util.ShutdownHookManager: Deleting directory /tmp/spark-43e0f38a-ec55-4052-9c64-8f053347854b/pyspark-56098864-fa4e-45ee-915e-f51c2c89a3df

**Comment by saksim** [comment]
原因：
https://blog.csdn.net/sinat_17697111/article/details/79927792
https://www.e-learn.cn/content/wangluowenzhang/707139

总结而言：
是由于PYTHON中各列具有空值。故而导致其类型与一般情况不同，故而创建时，产生类型冲突

**Comment by saksim** [comment]
> 原因：
> https://blog.csdn.net/sinat_17697111/article/details/79927792
> https://www.e-learn.cn/content/wangluowenzhang/707139
> 
> 总结而言：
> 是由于PYTHON中各列具有空值。故而导致其类型与一般情况不同，故而创建时，产生类型冲突

以上的方式并没有解决问题！

> 最优的方式是：
> （1）得到PD的DF的列名
> （2）将所有列包装为STRINGTYPE(PYSPARK.SQL内的类型)
> 
> ```
> from pyspark.sql.types import StructField, StringType, FloatType, StructType
> fields = [StructField(field_name, StringType(), True) for field_name in df.columns.values.tolist()]
> schema = StructType(fields)
> schemaPeople = spark.createDataFrame(df, schema)
> ```
>
